name = 'daliamcmillan'
main="worker/index.js"
compatibility_date = "2026-05-05"
compatibility_flags = [ "nodejs_compat" ]
preview_urls = true

[observability.logs]
enabled = false

[placement]
mode = "smart"

[assets]
directory = "./dist"
not_found_handling = "404-page"
html_handling = "force-trailing-slash"
run_worker_first = ["/~*"]

[[routes]]
pattern = "daliamcmillan.uk"
custom_domain = true
